name: NASA Example CI
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true #this is a built in function that tells it to not run tests in watch mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client